import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Auto-generated sidebar config.
 * Manually tweak groupings or ordering by adjusting this file.
 * See: https://docusaurus.io/docs/sidebar
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: "autogenerated",
      dirName: ".",
    },
  ],
};

export default sidebars;
